services:
  - type: web
    name: company-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn company_system.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: company_system.settings
      - key: PYTHON_VERSION
        value: 3.10
