# Generated by Django 5.1.7 on 2025-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
